site_name: Echter IT - Docs
theme:
  name: material
  icon:
    logo: fontawesome/solid/e
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

extra:
  social:
    - icon: simple/linkedin
      link: https://linkedin.com/in/echterit

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

copyright: Copyright &copy; 2024 <a href="https://www.echter-it.nl" target="_blank" rel="noopener">Echter IT.